name: vetlink1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  convex_bottom_bar: ^3.2.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  lottie: ^3.1.3
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/picture/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/picture/logo vetlink crop2.png"
  remove_alpha_ios: true
